export const NATIONALITY = {
  AU: "AU",
  BR: "BR",
  CA: "CA",
  CH: "CH",
  DE: "DE",
  DK: "DK",
  ES: "ES",
  FI: "FI",
  FR: "FR",
  GB: "GB",
  IE: "IE",
  IR: "IR",
  NO: "NO",
  NL: "NL",
  NZ: "NZ",
  TR: "TR",
  US: "US",
};
export const NATIONALITY_HUMAN_NAME = {
  [NATIONALITY.AU]: "Australian",
  [NATIONALITY.BR]: "Brazilian",
  [NATIONALITY.CA]: "Canadian",
  [NATIONALITY.CH]: "Chinese",
  [NATIONALITY.DE]: "German",
  [NATIONALITY.DK]: "Denmark",
  [NATIONALITY.ES]: "Spainish",
  [NATIONALITY.FI]: "Finnish",
  [NATIONALITY.FR]: "Franche",
  [NATIONALITY.GB]: "British",
  [NATIONALITY.IE]: "Irish",
  [NATIONALITY.IR]: "Iranian",
  [NATIONALITY.NO]: "Norwegian",
  [NATIONALITY.NL]: "Netherlandian",
  [NATIONALITY.NZ]: "New Zealandian",
  [NATIONALITY.TR]: "Turkish",
  [NATIONALITY.US]: "American",
};
